---
apiVersion: v1
kind: Secret
metadata:
  name: demo2-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/janus-idp-pittar/demo2-app-gitops